# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'qrApp.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

import sys
import vectors
from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_qrReaderApp(object):
    
    """QR Reader App for Detection, Creation or Edition of QR Codes"""

    def setupUi(self, qrReaderApp):
        qrReaderApp.setObjectName("qrReaderApp")
        qrReaderApp.resize(420, 260)
        qrReaderApp.setMinimumSize(QtCore.QSize(420, 260))
        qrReaderApp.setMaximumSize(QtCore.QSize(420, 260))
        qrReaderApp.setStyleSheet("background: #2A2E37;")
        self.qrapp_Buttons = QtWidgets.QDialogButtonBox(qrReaderApp)
        self.qrapp_Buttons.setGeometry(QtCore.QRect(330, 195, 81, 61))
        self.qrapp_Buttons.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.qrapp_Buttons.setStyleSheet("color: rgb(199, 199, 199);")
        self.qrapp_Buttons.setOrientation(QtCore.Qt.Vertical)
        self.qrapp_Buttons.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.qrapp_Buttons.setObjectName("qrapp_Buttons")
        self.objectInfo = QtWidgets.QGroupBox(qrReaderApp)
        self.objectInfo.setGeometry(QtCore.QRect(5, 99, 310, 151))
        self.objectInfo.setStyleSheet("color: rgb(14, 172, 186);")
        self.objectInfo.setObjectName("objectInfo")
        self.weight_Value = QtWidgets.QLineEdit(self.objectInfo)
        self.weight_Value.setGeometry(QtCore.QRect(130, 58, 41, 23))
        self.weight_Value.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.weight_Value.setStyleSheet("background: rgba(29, 222, 216, 0.1);\n"
                                        "color: rgb(199, 199, 199);")
        self.weight_Value.setText("")
        self.weight_Value.setAlignment(QtCore.Qt.AlignCenter)
        self.weight_Value.setReadOnly(True)
        self.weight_Value.setObjectName("weight_Value")
        self.object_Size_Value = QtWidgets.QLineEdit(self.objectInfo)
        self.object_Size_Value.setGeometry(QtCore.QRect(130, 88, 161, 23))
        self.object_Size_Value.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.object_Size_Value.setStyleSheet("background: rgba(29, 222, 216, 0.1);\n"
                                             "color: rgb(199, 199, 199);")
        self.object_Size_Value.setEchoMode(QtWidgets.QLineEdit.PasswordEchoOnEdit)
        self.object_Size_Value.setAlignment(QtCore.Qt.AlignCenter)
        self.object_Size_Value.setReadOnly(True)
        self.object_Size_Value.setObjectName("object_Size_Value")
        self.mass_Point_Label = QtWidgets.QLabel(self.objectInfo)
        self.mass_Point_Label.setGeometry(QtCore.QRect(5, 120, 111, 16))
        self.mass_Point_Label.setStyleSheet("color: rgb(199, 199, 199);")
        self.mass_Point_Label.setObjectName("mass_Point_Label")
        self.mass_Point_Value = QtWidgets.QLineEdit(self.objectInfo)
        self.mass_Point_Value.setGeometry(QtCore.QRect(130, 118, 161, 23))
        self.mass_Point_Value.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.mass_Point_Value.setStyleSheet("background: rgba(29, 222, 216, 0.1);\n"
                                            "color: rgb(199, 199, 199);")
        self.mass_Point_Value.setText("")
        self.mass_Point_Value.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.mass_Point_Value.setAlignment(QtCore.Qt.AlignCenter)
        self.mass_Point_Value.setReadOnly(True)
        self.mass_Point_Value.setObjectName("mass_Point_Value")
        self.dimmension_Label = QtWidgets.QLabel(self.objectInfo)
        self.dimmension_Label.setGeometry(QtCore.QRect(5, 60, 121, 16))
        self.dimmension_Label.setStyleSheet("color: rgb(199, 199, 199);")
        self.dimmension_Label.setObjectName("dimmension_Label")
        self.object_Name = QtWidgets.QLineEdit(self.objectInfo)
        self.object_Name.setGeometry(QtCore.QRect(130, 28, 161, 23))
        self.object_Name.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.object_Name.setWhatsThis("")
        self.object_Name.setStyleSheet("background: rgba(29, 222, 216, 0.1);\n"
                                       "color: rgb(199, 199, 199);")
        self.object_Name.setAlignment(QtCore.Qt.AlignCenter)
        self.object_Name.setDragEnabled(False)
        self.object_Name.setReadOnly(True)
        self.object_Name.setObjectName("object_Name")
        self.object_Size_Label = QtWidgets.QLabel(self.objectInfo)
        self.object_Size_Label.setGeometry(QtCore.QRect(5, 90, 81, 16))
        self.object_Size_Label.setStyleSheet("color: rgb(199, 199, 199);")
        self.object_Size_Label.setObjectName("object_Size_Label")
        self.object_Name_Label = QtWidgets.QLabel(self.objectInfo)
        self.object_Name_Label.setGeometry(QtCore.QRect(5, 30, 91, 16))
        self.object_Name_Label.setStyleSheet("color: rgb(199, 199, 199);")
        self.object_Name_Label.setObjectName("object_Name_Label")
        self.lenght_Value = QtWidgets.QLineEdit(self.objectInfo)
        self.lenght_Value.setGeometry(QtCore.QRect(190, 58, 41, 23))
        self.lenght_Value.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.lenght_Value.setStyleSheet("background: rgba(29, 222, 216, 0.1);\n"
                                        "color: rgb(199, 199, 199);")
        self.lenght_Value.setAlignment(QtCore.Qt.AlignCenter)
        self.lenght_Value.setReadOnly(True)
        self.lenght_Value.setObjectName("lenght_Value")
        self.height_Value = QtWidgets.QLineEdit(self.objectInfo)
        self.height_Value.setGeometry(QtCore.QRect(250, 58, 41, 23))
        self.height_Value.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.height_Value.setStyleSheet("background: rgba(29, 222, 216, 0.1);\n"
                                        "color: rgb(199, 199, 199);")
        self.height_Value.setAlignment(QtCore.Qt.AlignCenter)
        self.height_Value.setReadOnly(True)
        self.height_Value.setObjectName("height_Value")
        self.x1_Label = QtWidgets.QLabel(self.objectInfo)
        self.x1_Label.setGeometry(QtCore.QRect(175, 60, 13, 16))
        self.x1_Label.setStyleSheet("color: rgb(199, 199, 199);")
        self.x1_Label.setObjectName("x1_Label")
        self.x2_Label = QtWidgets.QLabel(self.objectInfo)
        self.x2_Label.setGeometry(QtCore.QRect(235, 60, 13, 16))
        self.x2_Label.setStyleSheet("color: rgb(199, 199, 199);")
        self.x2_Label.setObjectName("x2_Label")
        self.object_Size_Value.raise_()
        self.mass_Point_Label.raise_()
        self.mass_Point_Value.raise_()
        self.dimmension_Label.raise_()
        self.object_Name.raise_()
        self.object_Size_Label.raise_()
        self.object_Name_Label.raise_()
        self.height_Value.raise_()
        self.x1_Label.raise_()
        self.lenght_Value.raise_()
        self.x2_Label.raise_()
        self.weight_Value.raise_()
        self.qrapp_Line = QtWidgets.QFrame(qrReaderApp)
        self.qrapp_Line.setGeometry(QtCore.QRect(320, 10, 1, 240))
        self.qrapp_Line.setStyleSheet("background: rgba(29, 222, 216);")
        self.qrapp_Line.setFrameShape(QtWidgets.QFrame.VLine)
        self.qrapp_Line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.qrapp_Line.setObjectName("qrapp_Line")
        self.qr_Image = QtWidgets.QWidget(qrReaderApp)
        self.qr_Image.setGeometry(QtCore.QRect(60, 29, 81, 61))
        self.qr_Image.setStyleSheet("background: rgba(29, 222, 216, 0.1);\n"
                                    "color: rgb(199, 199, 199);")
        self.qr_Image.setObjectName("qr_Image")
        self.qr_Image_Label = QtWidgets.QLabel(qrReaderApp)
        self.qr_Image_Label.setGeometry(QtCore.QRect(70, 10, 71, 16))
        self.qr_Image_Label.setStyleSheet("color: rgb(14, 172, 186);")
        self.qr_Image_Label.setObjectName("qr_Image_Label")
        self.qrapp_New = QtWidgets.QPushButton(qrReaderApp)
        self.qrapp_New.setGeometry(QtCore.QRect(330, 10, 80, 23))
        self.qrapp_New.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.qrapp_New.setStyleSheet("color: rgb(199, 199, 199);")
        self.qrapp_New.setObjectName("qrapp_New")
        self.qrapp_Edit = QtWidgets.QPushButton(qrReaderApp)
        self.qrapp_Edit.setGeometry(QtCore.QRect(330, 40, 80, 23))
        self.qrapp_Edit.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.qrapp_Edit.setStyleSheet("color: rgb(199, 199, 199);")
        self.qrapp_Edit.setObjectName("qrapp_Edit")
        self.qrapp_Delete = QtWidgets.QPushButton(qrReaderApp)
        self.qrapp_Delete.setGeometry(QtCore.QRect(330, 70, 80, 23))
        self.qrapp_Delete.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.qrapp_Delete.setStyleSheet("color: rgb(199, 199, 199);")
        self.qrapp_Delete.setObjectName("qrapp_Delete")
        self.camera_Image = QtWidgets.QWidget(qrReaderApp)
        self.camera_Image.setGeometry(QtCore.QRect(152, 29, 111, 61))
        self.camera_Image.setStyleSheet("background: rgba(29, 222, 216, 0.1);\n"
                                        "color: rgb(199, 199, 199);")
        self.camera_Image.setObjectName("camera_Image")
        self.camera_Image_Label = QtWidgets.QLabel(qrReaderApp)
        self.camera_Image_Label.setGeometry(QtCore.QRect(160, 10, 101, 16))
        self.camera_Image_Label.setStyleSheet("color: rgb(14, 172, 186);")
        self.camera_Image_Label.setObjectName("camera_Image_Label")
        self.mass_Point_Label.setBuddy(self.mass_Point_Value)
        self.dimmension_Label.setBuddy(self.weight_Value)
        self.object_Size_Label.setBuddy(self.object_Size_Value)
        self.object_Name_Label.setBuddy(self.object_Name)
        self.x1_Label.setBuddy(self.weight_Value)
        self.x2_Label.setBuddy(self.weight_Value)
        self.qr_Image_Label.setBuddy(self.object_Name)
        self.camera_Image_Label.setBuddy(self.object_Name)

        self.retranslateUi(qrReaderApp)
        self.qrapp_Buttons.accepted.connect(qrReaderApp.accept)
        self.qrapp_Buttons.rejected.connect(qrReaderApp.reject)
        QtCore.QMetaObject.connectSlotsByName(qrReaderApp)


    def retranslateUi(self, qrReaderApp):
        _translate = QtCore.QCoreApplication.translate
        qrReaderApp.setWindowTitle(_translate("qrReaderApp", "QR Code Reader"))
        self.objectInfo.setTitle(_translate("qrReaderApp", "Object Information:"))
        self.weight_Value.setPlaceholderText(_translate("qrReaderApp", "W"))
        self.object_Size_Value.setWhatsThis(_translate("qrReaderApp", "1 - Small / 2 - Medium / 3 - Large"))
        self.object_Size_Value.setPlaceholderText(_translate("qrReaderApp", "1"))
        self.mass_Point_Label.setText(_translate("qrReaderApp", "CENTER OF MASS:"))
        self.mass_Point_Value.setPlaceholderText(_translate("qrReaderApp", "XX - XX"))
        self.dimmension_Label.setText(_translate("qrReaderApp", "DIMMENSION (CM):"))
        self.object_Name.setPlaceholderText(_translate("qrReaderApp", "BOX XXXX"))
        self.object_Size_Label.setText(_translate("qrReaderApp", "OBJECT SIZE:"))
        self.object_Name_Label.setText(_translate("qrReaderApp", "OBJECT NAME:"))
        self.lenght_Value.setPlaceholderText(_translate("qrReaderApp", "L"))
        self.height_Value.setPlaceholderText(_translate("qrReaderApp", "H"))
        self.x1_Label.setText(_translate("qrReaderApp", "X"))
        self.x2_Label.setText(_translate("qrReaderApp", "X"))
        self.qr_Image_Label.setText(_translate("qrReaderApp", "QR CODE:"))
        self.qrapp_New.setText(_translate("qrReaderApp", "NEW"))
        self.qrapp_Edit.setText(_translate("qrReaderApp", "EDIT"))
        self.qrapp_Delete.setText(_translate("qrReaderApp", "DELETE"))
        self.camera_Image_Label.setText(_translate("qrReaderApp", "CAMERA IMAGE:"))

if __name__ == "__main__":
    app = QtWidgets.QApplication(sys.argv)
    qrReaderApp = QtWidgets.QDialog()
    ui = Ui_qrReaderApp()
    ui.setupUi(qrReaderApp)
    qrReaderApp.show()
    sys.exit(app.exec_())

